### ISSUE TITLE
Resource files not found on the path

### ISSUE THREAD

**Issue by stujones11** [greenmoss/PyWavefront#6]
When I try to run the pyglet_demo I get the following error:

```
pyglet.resource.ResourceNotFoundException: Resource "/terran.png" was not found on the path.  Ensure that the filename has the correct captialisation.
```

I have tried re-exporting the model from blender using relative, absolute and auto path options but it still fails to find the textures. If I completely remove the texture linkage from the model then the demo runs as expected but without the texture.

I should also probably mention that I am using linux (xubuntu 16.04)

**Comment by stujones11** [comment]
Reverting to e2c123cfbda6e51e44dfb2319af37a768f7df3f0 appears to fix this issue for me so I guess it has something to do with #5

**Comment by greenmoss** [comment]
Check out #7; is it fixed with that? Let me know so I can release a new version.

**Comment by stujones11** [comment]
I can confirm [that] #7 fixes this issue for me, thank you.

**Comment by stujones11** [comment]
Sorry, I forgot to re-install and was still at e2c123cfbda6e51e44dfb2319af37a768f7df3f0 @greenmoss

Same error I'm afraid with current head.

**Comment by kaufManu** [comment]
I have the same problem with HEAD as well as e2c123c.

**Comment by greenmoss** [comment]
@kaufManu I just released and uploaded 0.1.3. Does this fix it for you?

**Comment by kaufManu** [comment]
@greenmoss Thanks for the update! I'm afraid it did not solve the problem, now it's telling me that it can't find the `.mtl` file. When I call `os.path.exists` on the resource path printed out by the exception, it returns true.

**Comment by jerekshoe** [comment]
I'm sorry if I missed something but are you running into issues with the examples or custom files? Also can you tell us what os and version of python you are using?

**Comment by kaufManu** [comment]
Sorry for not being too specific, here is an example: The following two lines are in a python script that lies somewhere in my PyCharm Project Directory:

```
print os.path.exists('D:\PyWavefront\example/earthmap.2k.jpg')
mesh = pywavefront.Wavefront('D:\PyWavefront\example\earth.obj')
```
This then prints
```
True
...
pyglet.resource.ResourceNotFoundException: Resource "D:\PyWavefront\example/earthmap.2k.jpg" was not found on the path.  Ensure that the filename has the correct captialisation.
```
If I do the exact same thing, but copy the python script to the location where the OBJ files are and execute it from there, it works. The issue is both with the example and custom files.

I'm on Windows 10, Python 2.7

**Comment by jerekshoe** [comment]
@kaufManu thanks for the additional information. I was able to recreate the issue that you had and have created a new pull request to try and fix this issue once and for all. Once @greenmoss has a change to review it, it should be ready for you to test.

**Comment by greenmoss** [comment]
Merged; please build the binary and test with pip, then I will upload a new release to pypi

**Comment by kaufManu** [comment]
@greenmoss, @jerekshoe Thanks for the update! I just tested it and can confirm that it fixes the issue. When you say "test with pip" what exactly do you mean (sorry, kinda new to Python projects :))? I just pulled the latest changes, did ´python setup.py install´ and tested with a on-the-fly script. Is there anything else you need me to do?

**Comment by greenmoss** [comment]
@kaufManu are you able to generate the pip file, then pip install it, and have it fix the issue?

**Comment by kaufManu** [comment]
@greenmoss I'm sorry but I still don't understand. What is the pip file? If you want me to pip install it, doesn't it already have to be in the PyPI? This would in turn require me to create a user there, if I'm not mistaken ... sorry for the trouble ...

**Comment by greenmoss** [comment]
I think this was done already
